# Generated by Django 4.2.5 on 2023-09-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название часов:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание часов:')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Добавьте фото часов:')),
                ('review', models.URLField(verbose_name='Укажите ссылку')),
                ('model', models.CharField(choices=[('B650WB-1B', 'B650WB-1B'), ('MTP-VD03B-1A', 'MTP-VD03B-1A'), ('MTP-1308D-1A', 'MTP-1308D-1A'), ('MTP-VD01G-1B', 'MTP-VD01G-1B')], max_length=100, verbose_name='Укажите модель часов:')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену часов:')),
                ('director', models.CharField(max_length=100, null=True, verbose_name='Укажите авторство:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
            },
        ),
    ]
