# Generated by Django 4.2.5 on 2023-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_object', models.CharField(max_length=100, verbose_name='Укажите название часов:')),
                ('review_created_at', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='Отзыв:')),
                ('review_start', models.CharField(choices=[('Оценка: 1', 'Оценка: 1'), ('Оценка: 2', 'Оценка: 2'), ('Оценка: 3', 'Оценка: 3'), ('Оценка: 4', 'Оценка: 4'), ('Оценка: 5', 'Оценка: 5')], max_length=100, verbose_name='Укажите свою оценку:')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
